import OSLog
import SwiftUI
import RealityKit

private let immersiveTrackingLogger = Logger(
    subsystem: Bundle.main.bundleIdentifier ?? "com.darkstring.Astra",
    category: "ImmersiveTracking"
)

struct ImmersiveView: View {
    @Environment(AppModel.self) private var appModel
    @State private var subscriptions: [EventSubscription] = []
    @State private var spatialTrackingSession = SpatialTrackingSession()

    var body: some View {
        RealityView { content in
            let placement = appModel.placement
            immersiveTrackingLogger.notice("RealityView content closure started; placement.isReady=\(placement.isReady, privacy: .public)")
            // SwiftUI owns the entity passed to content.add. Give each RealityView
            // construction a fresh container instead of reusing an already-parented root.
            let container = Entity()
            placement.root.removeFromParent()
            container.addChild(placement.root)
            placement.sceneRoot.removeFromParent()
            container.addChild(placement.sceneRoot)
            content.add(container)
            subscriptions = [
                content.subscribe(to: ManipulationEvents.WillBegin.self) { event in
                    placement.manipulationBegan(event.entity)
                },
                content.subscribe(to: ManipulationEvents.DidUpdateTransform.self) { event in
                    placement.manipulationUpdated(event.entity)
                },
                content.subscribe(to: ManipulationEvents.WillEnd.self) { event in
                    placement.manipulationEnded(event.entity)
                }
            ]

            // SurroundingsLight needs the scene-understanding mesh generated by
            // a running SpatialTrackingSession in order to illuminate real
            // walls and other opaque surfaces.
            let configuration = SpatialTrackingSession.Configuration(
                tracking: [.world],
                sceneUnderstanding: [.collision, .physics]
            )
            let spatialTrackingStarted = Date()
            immersiveTrackingLogger.notice("Starting SpatialTrackingSession: tracking=world, sceneUnderstanding=collision+physics")
            if let unavailable = await spatialTrackingSession.run(configuration) {
                let unavailableDescription = String(describing: unavailable)
                immersiveTrackingLogger.warning(
                    "SpatialTrackingSession returned unavailable after \(Date().timeIntervalSince(spatialTrackingStarted), privacy: .public)s: \(unavailableDescription, privacy: .public)"
                )
                if !unavailable.missingAuthorizations.isEmpty {
                    appModel.spatialTrackingWarning = "墙面投影需要世界感知权限，请在系统提示中允许；如果之前拒绝过，请到设置中重新开启。"
                } else {
                    appModel.spatialTrackingWarning = "当前设备未提供场景理解，墙面投影暂时不可用。"
                }
            } else {
                immersiveTrackingLogger.notice(
                    "SpatialTrackingSession completed successfully after \(Date().timeIntervalSince(spatialTrackingStarted), privacy: .public)s"
                )
                appModel.spatialTrackingWarning = nil
            }
            immersiveTrackingLogger.info("Loading model after SpatialTrackingSession")
            await placement.load()
            immersiveTrackingLogger.notice("Model load returned; placement.isReady=\(placement.isReady, privacy: .public)")
        }
        // Same routing as viewshine's MainImmersiveView: accept any entity,
        // then resolve the specific key. No component-filtered gesture query.
        .gesture(TapGesture().targetedToAnyEntity().onEnded { value in
            appModel.placement.keyboardControls.handleTap(on: value.entity)
        })
        .onChange(of: appModel.placement.screenVideo.showModelInputRegions) { _, visible in
            appModel.placement.keyboardControls.setDebugVisible(visible)
        }
        .onDisappear {
            immersiveTrackingLogger.notice("ImmersiveView disappeared; stopping spatial tracking")
            subscriptions.forEach { $0.cancel() }
            subscriptions.removeAll()
            appModel.immersiveSpaceDidOpen = false
            appModel.placement.unload()
            appModel.spatialTrackingWarning = nil
            Task { await spatialTrackingSession.stop() }
        }
    }
}
